### ISSUE TITLE
Callback-based Gauge?

### ISSUE THREAD

**Issue by plainlystated** [prometheus/client_ruby#171] opened 2019-12-20 20:38 UTC
Is there any way to implement a callback-based gauge?  This would be very useful for metrics that aren't related to the threads or processes of the server.  For example, the docs mention a gauge for temperature:

```
gauge = Prometheus::Client::Gauge.new(:room_temperature_celsius, docstring: '...', labels: [:room])
```

This requires that there is some mechanism that continually updates the gauge via ```gauge.set```, and hopefully the cadence of this mechanism matches the cadence of the scrape.  It would be really nice to instead specify a callback and have the value calculated as needed.

This is how the python library works, which is great:

```
d = Gauge('room_temperature_celsius', 'Temp of room', ['room'])
d.labels('Room 1').set_function(lambda: ...))
```

**Comment by dmagliola** [comment] 2019-12-20 22:30
Hello,
Thank you for opening the issue. 
The solution for this is Custom Collectors, which we're hoping to implement soon. 
We're tracking that discussion on issue #90 

I'm closing this issue as a duplicate of that one. Wir keep any updates to the other issue. 

Thank you!

**Closed by dmagliola** 2019-12-20 22:30 UTC

**Comment by plainlystated** [comment] 2019-12-21 15:19
Great, thanks for the update. I'll keep an eye on that ticket.
