### ISSUE TITLE
K8s nfs shared store file writing error

### ISSUE THREAD

**Issue by ShamoX** [prometheus/client_ruby#223] opened 2021-04-19 13:51 UTC
Hi,

We started to use your gem few weeks ago and I wanted to start by thanking you all about what you made.

We use this Gem in a context of a Rails 5.2 / sidekiq application that we run in separated pods all the components :

- Rails application in a pod, using [Yabeda::Prometheus::Exporter](https://github.com/yabeda-rb/yabeda-prometheus) to access the metrics on /metrics and the files are read from /app/tmp/metrics which is a [PersistentVolume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) with `ReadWriteMany` access mode.
- Sidekiq workers has access to this volume at the same path, and are in charge through an ActiveJob to collect the metrics every minutes (ActiveJob created by a dedicated cron pod)

We experienced rapidly and error (Errno::ESTALE) :

> /bundle/ruby/2.5.0/gems/prometheus-client-2.1.0/lib/prometheus/client/data_stores/direct_file_store.rb:284:in `seek'
> /bundle/ruby/2.5.0/gems/prometheus-client-2.1.0/lib/prometheus/client/data_stores/direct_file_store.rb:284:in `write_value'                                               
> /bundle/ruby/2.5.0/gems/prometheus-client-2.1.0/lib/prometheus/client/data_stores/direct_file_store.rb:104:in `block in set'                                              
> /bundle/ruby/2.5.0/gems/prometheus-client-2.1.0/lib/prometheus/client/data_stores/direct_file_store.rb:161:in `block in in_process_sync'                                  
> /usr/local/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'                                                                                                                                                      
> /bundle/ruby/2.5.0/gems/prometheus-client-2.1.0/lib/prometheus/client/data_stores/direct_file_store.rb:161:in `in_process_sync'
> ...

Since it is an error that may be raised by the filesystem, we don't see where to manage it elsewhere than in your library code.

So I'm about to create a PullRequest that should fix it with a test case.

I'll be grateful if you can challenge it in the form and content.

Best

**Comment by dmagliola** [comment] 2021-05-12 19:57
Hello,
Sorry for my very late response...

I believe the issue is putting the files in a PersistentVolume.

To make sure I understand:
- Does this mean that when your pod restarts, it'll still have the files from an old pod run?
- Does it also mean that if you have multiple pods, they will all mount the same shared directory?

You do not want either of those to be the case.
- If multiple pods share files, you will get this problem, as different pods will be writing each other's files. And you will not be able to know, in your metrics, which pod they are coming from.
- If you keep your files after a restart, your metrics will not reset on restart, and you will accumulate large numbers of files which will become problematic quite quickly.

Normally, you would put these metrics on a pods `/tmp` directory, and let them die when a pod dies.

Am I misunderstanding the situation here?

Once again, very sorry for the very late response,. it's been a hectic few weeks

**Comment by ShamoX** [comment] 2021-05-12 21:11
No problem for the late response, we have all our rushes ;)

You understand the situation, and I'm well aware of the problematics.
I would have preferred a Database version of the storage of course but didn't had the time to develop it and didn't found one.

Some precisions :
* Even if the folder is shared, the process pid may not be the same (but that not pretty sure)
* I need it shared, because I have pod for the my default queue workers that generates the metrics and those needs to be accessible to the rails application that reads them.
* When a pod starts (default-worker), it deletes all the present files (to prevent accumulation)

That last point lead to the "feature" i need (the capability of the library to accept that the file it writes on, may have been deleted by someone). This is really not perfect, but at least, it allow not to restart the pod (re-generating the problem) each time. Without the fix I propose, in more of the problems you described, I had my system totally enable to deliver metrics until the next release, then it goes of few ours later.

Since for all my metrics I only use the last value, it makes a sens (a little ?).

Example of the PID in my pods:
```
$ kubectl -n xxx-production exec -it production-default-xxx-dpbwn -- ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   8584  3388 ?        Ss   May10   0:00 /bin/bash ./doc
root        87  1.1  7.6 1725844 1142704 ?     Sl   May10  38:27 sidekiq 6.0.7 a
root     12677  0.0  0.0  12356  3080 pts/0    Rs+  21:00   0:00 ps -aux
$ kubectl -n xxx-production exec -it production-default-xxx-ltstv -- ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   8584  2800 ?        Ss   May10   0:00 /bin/bash ./doc
root        86  1.1  7.2 1547664 1082064 ?     Sl   May10  39:03 sidekiq 6.0.7 a
$
```

On other deployment I see that the pid is also 86...

**Comment by Sinjo** [comment] 2021-05-12 22:57
Hey, thanks for raising this with us @ShamoX. I'm with @dmagliola on this one.

I don't think mounting the same filesystem into multiple pods is a use-case we can reliably support in `DirectFileStore`.

As you've noted, PID collisions are going to happen, and that breaks our assumptions of each individual file only being written by one process.

I'm not sure exactly what semantics you'll get from different implementations of `ReadWriteMany` persistent volumes (e.g. NFS, as you mentioned it in the title).  I think the state of the internal store _might_ stay consistent if we properly handled `ESTALE` and reopened the file, but I wouldn't feel confident shipping that code.

There's also file locking to consider. I'd have to dig into the details of how Ruby's `File.flock` is implemented to be totally sure (I'd guess `fcntl`), but my understanding is that NFS (which you mentioned in the title) implementations are often not as reliable at implementing it as a local file system.

Overall, I feel like we'd be opening ourselves up to lots of new avenues for bugs to creep in, and I think there are simpler approaches to solving the problem you're facing, where you have some metrics in a process that doesn't have a HTTP server in it and you need a way of exporting them.

One thing we've done at work (http://github.com/gocardless) is to expose a small web server on an extra thread in non-web-server processes. There's also the push gateway, which your worker processes could send their metrics to. Would either of those work for you?

**Comment by dmagliola** [comment] 2021-05-21 19:08
Following on from what Chris said above, I agree we shouldn't be supporting this use case, so i'm closing this issue.

To expand on Chris's mention of exposing a small web server, here is one example of how you could do that, from one of GoCardless's public repos: https://github.com/gocardless/que/blob/master/bin/que#L118-L156

Hope that helps!

**Closed by dmagliola** 2021-05-21 19:08 UTC
