### ISSUE TITLE
Sliding window implementation for summaries

### ISSUE THREAD

**Issue by Bruno-DaSilva** [prometheus/client_ruby#87] opened 2018-04-27 18:50 UTC
So in most cases with time series data, it doesnt make sense to have cumulative summaries. I've implemented sliding windows in a way that works for my uses, but I thought I'd put it here in case you'd like to modify it slightly for the full gem

TimeWindowEstimator class
```ruby
# This class is a wrapper around a single Quantile::Estimator, which is used to hold data for summaries
# It maintains a ring buffer of Estimators to provide quantiles over a sliding windows of time.
module Quantile
  class TimeWindowEstimator
    attr_reader :invariants

    def initialize(invariants, max_age_seconds, age_buckets)
      @invariants = invariants
      @ring_buffer = []
      age_buckets.times { @ring_buffer.push(Estimator.new(*invariants)) }
      @current_bucket = 0
      @last_rotated_time = Time.now
      @duration_between_rotations_seconds = max_age_seconds / age_buckets
    end

    def query(quantile)
      current_estimator = rotate
      current_estimator.query(quantile)
    end

    def observe(value)
      rotate
      @ring_buffer.each do |estimator|
        estimator.observe(value)
      end
    end

    def sum
      current_estimator = rotate
      current_estimator.sum
    end

    def observations
      current_estimator = rotate
      current_estimator.observations
    end

    private

    def rotate
      time_since_last_rotate = Time.now - @last_rotated_time
      while time_since_last_rotate > @duration_between_rotations_seconds
        # Clear the current bucket
        @ring_buffer[@current_bucket] = Estimator.new(*@invariants)

        @current_bucket += 1
        @current_bucket = 0 if @current_bucket >= @ring_buffer.length

        time_since_last_rotate -= @duration_between_rotations_seconds
        @last_rotated_time += @duration_between_rotations_seconds
      end
      @ring_buffer[@current_bucket]
    end
  end
end
```

TimeWindowSummary
```ruby
require 'quantile'
require 'prometheus/client/summary'
require_relative 'time_window_estimator'

# rubocop:disable Metrics/LineLength
# rubocop:disable Metrics/ParameterLists

module Prometheus
  module Client
    # Summary is an accumulator for samples. It captures Numeric data and provides an efficient quantile calculation mechanism.
    # TimeWindowSummary is a summary but with a sliding window of time for metrics
    class TimeWindowSummary < Summary
      attr_reader :invariants, :max_age_seconds, :num_buckets

      # Time Window Summaries should have:
      # name: name of the metric
      # docstring: description of the metric
      # max_age_seconds: Set the duration of the time window is, i.e. how long observations are kept before they are discarded
      # invariants: Array of quantiles and their given error bounds
      # num_buckets: Set the number of buckets used to implement the sliding time window. If your time window is 10 minutes,
      #     and you have ageBuckets=5, buckets will be switched every 2 minutes.
      #     The value is a trade-off between resources (memory and cpu for maintaining the bucket) and how smooth the time window is moved.
      # base_labels: optional set of labels
      def initialize(name, docstring, invariants, max_age_seconds, num_buckets, base_labels = {})
        @invariants = invariants
        @max_age_seconds = max_age_seconds
        @num_buckets = num_buckets

        super(name, docstring, base_labels)
      end

      # Type must be summary so that the prometheus scraper still thinks its a valid type
      def type
        :summary
      end

      private

      def default
        Quantile::TimeWindowEstimator.new(@invariants, @max_age_seconds, @num_buckets)
      end
    end
  end
end
# rubocop:enable Metrics/LineLength
# rubocop:enable Metrics/ParameterLists
```

**Comment by Bruno-DaSilva** [comment] 2018-04-27 18:54
I've confirmed it's working as intended, at least in its current implementation. It also allows for custom invariants which is currently not supported with regular summaries in this gem at the moment.

@grobie please feel free to take and use this in the gem in any regard. I took much of the implementation from the `client_java` library.

**Comment by Bruno-DaSilva** [comment] 2018-04-27 18:55
The only thing I'm unsure of is what structure of interface to use, seeing as you need to pass in invariants/max_age_seconds/num_buckets. They can't be optional because base_labels is taking all the rest of the args...

**Comment by grobie** [comment] 2018-05-04 12:02
Thanks @Bruno-DaSilva, this would solve #12! The design of the interface is certainly something which needs to be improved. The whole concept of base label has been found unnecessary in the Prometheus ecosystem and is often even an anti-pattern.

**Comment by grobie** [comment] 2018-05-04 12:12
Closing this as duplicate of #12. I'd love to accept a PR for that @Bruno-DaSilva!

**Closed by grobie** 2018-05-04 12:12 UTC
